<header>
  <h1>intro to optimization</h1>
</header>
<h2>background</h2>
<p>
I'm using the material from the course 
<a href="https://uwflow.com/course/co250">CO250</a> at the 
<a href="https://uwaterloo.ca">University of Waterloo</a> which uses the book 
<a href="http://a.co/9jXMHda">"A Gentle Introduction to Optimization"</a>, 
which is a quite subjective title for a textbook. I'll include any other 
references I come across while learning.
</p>
<h2>topics</h2>
<ul>
  <li><a href="prereqs.html">prereqs</a></li>
  <li><a href="programs.html">1.0 Intro to Programs</a></li>
  <ul>
    <li><a href=".html">1.1 Modeling Linear Programs</a></li>
    <li><a href=".html">1.2 Modeling Integer Programs</a></li>
    <li><a href=".html">1.3 Modeling Non-linear Programs</a></li>
  </ul>
  <li><a href=".html">2.0 Linear Programs</a></li>
  <ul>
    <li><a href=".html">2.1 Outcomes</a></li>
    <li><a href=".html">2.2 Standard Equality Form</a></li>
    <li><a href=".html">2.3 Bases</a></li>
    <li><a href=".html">2.4 Canonical Form</a></li>
  </ul>
</ul>
