<header>
  <h1>intro to optimization: <em>prereqs</em></h1>
</header>
<h2>linear algebra</h2>
<h3>matrix multiplication</h3>
<p>
There will be a lot of matrix multiplication, so it's important that we
understand what it is and does.

<br><br>

For me it was never clear in my head how matrix multiplication works or why it's
defined the way it is. I sort of just memorized how it works with a physical
mnemonic where I turn my head to the right and then a downwards nod and that's
it.

A good way to think about matrix multiplication is described <a
href="https://math.stackexchange.com/a/31729">here</a>.

Matrix multiplication is defined the way it is because it is the composition of
two linear functions, which results in a new linear function.


</p>
<h3>linear independence</h3>
<h3>row reduction, solving a system of equations</h3>
