<header>
  <h1>optimization: <em>programs</em></h1>
</header>
<h2>introduction</h2>
Alright, like me, you probably heard about these math program things that
aren't really related to computers. So it turns out mathematical programming
is actually just a synonym for mathematical optimization. So no computer code
here.
<br><br>
Okay so mathematical optimization. This is what actually caught my attention.
The whole premise here is that we have a function of some parameters that we
want to maximize or minimize. Like dollars $$$!
<br><br>
For instance let's think about making a run for groceries. We ran out of apples,
bananas and clementines. 
